AWSTranslatePost/Models/ErrorViewModel.cs
using System;

namespace AWSTranslatePost.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AWSTranslatePost/Controllers/AWSTranslateController.cs
using Amazon.Runtime;
using Amazon.Runtime.CredentialManagement;
using Amazon.Translate;
using Amazon.Translate.Model;
using AWSTranslatePost.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AWSTranslatePost.Controllers
{
    public class AWSTranslateController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string texto, string lenguaje)
        {
            if (texto == null || lenguaje == null)
            {
                ViewBag.Mensaje = "Rellene todos los campos.";
            }
            else
            {
                using(IAmazonTranslate client = new AmazonTranslateClient())
                {
                    TranslateTextRequest request = new TranslateTextRequest()
                    {
                        SourceLanguageCode = "auto",
                        TargetLanguageCode = lenguaje,
                        Text = texto
                    };
                    TranslateTextResponse resultado = await client.TranslateTextAsync(request);
                    if (resultado.HttpStatusCode != System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.Mensaje = "Se ha producido un error en la traducción.";
                    }
                    else
                    {
                        ViewBag.Traduccion = resultado.TranslatedText;
                    }
                }
            }
            return View();
        }
    }
}

AWSTranslatePost/Controllers/HomeController.cs
using AWSTranslatePost.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AWSTranslatePost.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AWSTranslatePost/Views/AWSTranslate/Index.cshtml
<h1>AWS Translate</h1>

<h3 style="color:firebrick">@ViewBag.Mensaje</h3>

<form method="post" style="margin-bottom: 50px">
    <div class="form-group">
        <label>Lenguaje:</label>
        <input type="text" name="lenguaje" class="form-control" />
    </div>
    <div class="form-group">
        <label>Texto:</label>
        <textarea name="texto" class="form-control" rows="4"></textarea>
    </div>
    <button type="submit" class="btn btn-info">Traducir</button>
</form>

<label>Traducción:</label>
<textarea name="texto" class="form-control" rows="4">@ViewBag.Traduccion</textarea>

AWSTranslatePost/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AWSTranslatePost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AWSTranslatePost</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AWSTranslatePost</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AWSTranslate" asp-action="Index">AWS Translate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AWSTranslatePost - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>